name: Create a draft release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build_sources:
    name: Build sources
    uses: ./.github/workflows/build.yml

  create_draft_release:
    name: Create a draft release
    needs: build_sources
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    
    - name: Fetch build artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Create Windows assets
      run: |
        mkdir randomrolls/tools
        cp cpuid-rdrand.exe randomrolls/tools/
        cp cpuid-rdrand.pdb randomrolls/tools/
        cp README.md randomrolls/readme.txt
        7z a randomrolls-win.zip randomrolls Setup-randomrolls.exe
    
    - name: Create Linux assets
      run: |
        cp rand.so randomrolls/
        cp README.md randomrolls/readme.txt
        7z a randomrolls-linux.zip randomrolls/rand.so randomrolls/readme.txt

    - name: Create a draft release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        artifacts: randomrolls-win.zip, randomrolls-linux.zip
        artifactContentType: application/zip
        commit: ${{github.ref}}
        draft: true
        tag: ${{github.ref}}
